<?php

declare(strict_types=1);

namespace OpenEHR\Assistant\Integrations\Repository;

use OpenEHR\Assistant\Domain\Repository\ModelRepository;
use RuntimeException;
use InvalidArgumentException;

/** Single-node atomic project snapshots with optimistic concurrency and immutable artefact revisions. */
final class FileSystemRepository implements ModelRepository
{
    private readonly string $root;

    public function __construct(string $root)
    {
        if (!str_starts_with($root, '/') || str_contains($root, "\0")) {
            throw new InvalidArgumentException('Repository root must be an absolute path.');
        }
        $this->assertNoSymlinks($root);
        if (!is_dir($root) && !mkdir($root, 0700, true) && !is_dir($root)) {
            throw new RuntimeException('REPOSITORY_UNAVAILABLE');
        }
        $this->root = realpath($root) ?: throw new RuntimeException('REPOSITORY_UNAVAILABLE');
    }

    public function capabilities(): array
    {
        return ['storage' => true, 'versioning' => true, 'history' => true, 'branching' => false,
            'diff' => false, 'reviews' => false, 'approvals' => false, 'locking' => true,
            'webhooks' => false, 'ci' => false, 'releaseTags' => false, 'offline' => true];
    }

    public function listProjects(): array
    {
        $items = [];
        foreach (glob($this->root . '/*.json') ?: [] as $path) {
            $items[] = $this->getProject(basename($path, '.json'));
        }
        return $items;
    }

    public function getProject(string $id): array
    {
        return $this->load($id)['project'];
    }

    public function createProject(string $id, string $name, string $description): array
    {
        if (trim($name) === '' || strlen($name) > 200 || strlen($description) > 10000) {
            throw new InvalidArgumentException('Invalid project name or description.');
        }
        return $this->transaction($id, function (array $state) use ($id, $name, $description): array {
            if ($state !== []) {
                throw new RuntimeException('PROJECT_ALREADY_EXISTS');
            }
            $now = gmdate(DATE_ATOM);
            $project = ['id' => $id, 'name' => $name, 'description' => $description, 'status' => 'ACTIVE',
                'revision' => bin2hex(random_bytes(16)), 'created_at' => $now, 'updated_at' => $now];
            return [['project' => $project, 'artifacts' => [], 'history' => []], $project];
        }, true);
    }

    public function archiveProject(string $id, string $expectedRevision): array
    {
        return $this->transaction($id, function (array $state) use ($expectedRevision): array {
            if ($state['project']['revision'] !== $expectedRevision) {
                throw new RuntimeException('REVISION_CONFLICT');
            }
            $state['project']['status'] = 'ARCHIVED';
            $state['project']['revision'] = bin2hex(random_bytes(16));
            return [$state, $state['project']];
        });
    }

    public function listArtifacts(string $project): array
    {
        return array_values($this->load($project)['artifacts']);
    }

    public function getArtifact(string $project, string $path, ?string $revision = null): array
    {
        $this->artifactPath($path);
        $state = $this->load($project);
        if ($revision === null) {
            return $state['artifacts'][$path] ?? throw new RuntimeException('ARTIFACT_NOT_FOUND');
        }
        foreach ($state['history'][$path] ?? [] as $item) {
            if ($item['revision'] === $revision) {
                return $item;
            }
        }
        throw new RuntimeException('VERSION_NOT_FOUND');
    }

    public function saveArtifact(string $project, string $path, string $content, array $metadata, ?string $expectedRevision): array
    {
        $this->artifactPath($path);
        if (strlen($content) > 2097152 || strlen(json_encode($metadata, JSON_THROW_ON_ERROR)) > 65536) {
            throw new InvalidArgumentException('ARTIFACT_TOO_LARGE');
        }
        // Governance fields can only be generated by a trusted lifecycle service, never claimed by an agent.
        foreach (['status', 'validation', 'approved_by', 'released_by', 'revision', 'created_by'] as $field) {
            if (array_key_exists($field, $metadata)) {
                throw new InvalidArgumentException('RESERVED_METADATA_FIELD: ' . $field);
            }
        }
        return $this->transaction($project, function (array $state) use ($path, $content, $metadata, $expectedRevision): array {
            $this->assertActive($state);
            $current = $state['artifacts'][$path] ?? null;
            if (($current['revision'] ?? null) !== $expectedRevision) {
                throw new RuntimeException('REVISION_CONFLICT');
            }
            $artifact = ['path' => $path, 'content' => $content, 'metadata' => $metadata, 'status' => 'DRAFT',
                'revision' => bin2hex(random_bytes(16)), 'sha256' => hash('sha256', $content),
                'updated_at' => gmdate(DATE_ATOM), 'provider' => 'filesystem'];
            $state['artifacts'][$path] = $artifact;
            $state['history'][$path][] = $artifact;
            return [$state, $artifact];
        });
    }

    public function deleteArtifact(string $project, string $path, string $expectedRevision): void
    {
        $this->artifactPath($path);
        $this->transaction($project, function (array $state) use ($path, $expectedRevision): array {
            $this->assertActive($state);
            $current = $state['artifacts'][$path] ?? throw new RuntimeException('ARTIFACT_NOT_FOUND');
            if ($current['revision'] !== $expectedRevision) {
                throw new RuntimeException('REVISION_CONFLICT');
            }
            $current['status'] = 'DELETED';
            $current['revision'] = bin2hex(random_bytes(16));
            $current['updated_at'] = gmdate(DATE_ATOM);
            $state['history'][$path][] = $current;
            unset($state['artifacts'][$path]);
            return [$state, []];
        });
    }

    public function history(string $project, string $path): array
    {
        $this->artifactPath($path);
        return $this->load($project)['history'][$path] ?? [];
    }

    private function artifactPath(string $path): void
    {
        if (strlen($path) > 240 || !preg_match('~^(requirements|archetypes|templates|terminology|aql|tests|validation|decisions|documentation)/[A-Za-z0-9_./-]+$~D', $path)
            || str_contains($path, '..') || str_contains($path, '//') || str_ends_with($path, '/')) {
            throw new InvalidArgumentException('INVALID_ARTIFACT_PATH');
        }
    }

    private function projectPath(string $id): string
    {
        if (!preg_match('/^[a-zA-Z0-9][a-zA-Z0-9_-]{0,63}$/D', $id)) {
            throw new InvalidArgumentException('INVALID_PROJECT_ID');
        }
        $path = $this->root . '/' . $id . '.json';
        $this->assertNoSymlinks($path);
        return $path;
    }

    private function assertNoSymlinks(string $path): void
    {
        $current = '';
        foreach (explode('/', $path) as $part) {
            if ($part === '') {
                continue;
            }
            if ($part === '..' || $part === '.') {
                throw new InvalidArgumentException('INVALID_REPOSITORY_PATH');
            }
            $current .= '/' . $part;
            if (is_link($current)) {
                throw new InvalidArgumentException('REPOSITORY_SYMLINK_FORBIDDEN');
            }
        }
    }

    /**
     * @return array<string, mixed> */
    private function load(string $id): array
    {
        $path = $this->projectPath($id);
        if (!is_file($path)) {
            throw new RuntimeException('PROJECT_NOT_FOUND');
        }
        if (filesize($path) > 33554432) {
            throw new RuntimeException('PROJECT_SIZE_LIMIT');
        }
        $state = json_decode((string) file_get_contents($path), true, 64, JSON_THROW_ON_ERROR);
        if (!is_array($state) || !isset($state['project'], $state['artifacts'], $state['history'])) {
            throw new RuntimeException('REPOSITORY_INVALID_SNAPSHOT');
        }
        return $state;
    }

    /**
     * @param array<string, mixed> $state */
    private function assertActive(array $state): void
    {
        if ($state['project']['status'] !== 'ACTIVE') {
            throw new RuntimeException('PROJECT_ARCHIVED');
        }
    }

    /**
     * @param callable(array<string, mixed>): array{array<string, mixed>, array<string, mixed>} $operation
     *
     * @return array<string, mixed>
     */
    private function transaction(string $id, callable $operation, bool $create = false): array
    {
        $path = $this->projectPath($id);
        $this->assertNoSymlinks($path . '.lock');
        $lock = fopen($path . '.lock', 'c');
        if ($lock === false || !flock($lock, LOCK_EX)) {
            throw new RuntimeException('REPOSITORY_LOCK_FAILED');
        }
        $temporary = null;
        try {
            $state = $create && !file_exists($path) ? [] : $this->load($id);
            [$next, $result] = $operation($state);
            $next['project']['updated_at'] = gmdate(DATE_ATOM);
            $data = json_encode($next, JSON_PRETTY_PRINT | JSON_THROW_ON_ERROR);
            if (strlen($data) > 33554432) {
                throw new RuntimeException('PROJECT_SIZE_LIMIT');
            }
            $temporary = tempnam($this->root, '.write-');
            if ($temporary === false || file_put_contents($temporary, $data, LOCK_EX) !== strlen($data)) {
                throw new RuntimeException('REPOSITORY_WRITE_FAILED');
            }
            chmod($temporary, 0600);
            $this->assertNoSymlinks($path);
            if (!rename($temporary, $path)) {
                throw new RuntimeException('REPOSITORY_WRITE_FAILED');
            }
            return $result;
        } finally {
            if (is_string($temporary) && is_file($temporary)) {
                unlink($temporary);
            }
            flock($lock, LOCK_UN);
            fclose($lock);
        }
    }
}
